<?php 
function template_meta_7b29c25f17dbd6324a41e78035d6db11($t){

}
function template_7b29c25f17dbd6324a41e78035d6db11($t){
?><h1>404 Not Found</h1>
<p>Sorry, the requested page doesn't exist</p>
<p style="font-size:0.6em; font-style:italic">Page generated by <a href="http://jelix.org">Jelix</a>.</p><?php 
}
?>